import { Link } from 'react-router-dom'
import { curriculum } from '../content/curriculum'
import { useProgress } from '../components/learning/ProgressProvider'
import { Card } from '../components/ui/Card'
import { ProgressBar } from '../components/ui/ProgressBar'

export function DashboardPage() {
  const { status, error, overallProgress, continueLearning, getTopicProgress, recentLessons } = useProgress()
  const first = curriculum[0]?.lessons[0]
  if (status === 'loading') return <main className="mx-auto w-full max-w-320 px-5 py-16 sm:px-10 lg:px-20"><p className="type-label text-accent">Your learning</p><div className="mt-6 h-48 animate-pulse rounded-md bg-surface-alt" aria-label="Loading progress" /></main>
  if (status === 'error') return <main className="mx-auto w-full max-w-320 px-5 py-16 sm:px-10 lg:px-20"><h1 className="type-h1">Your learning</h1><p className="mt-5 text-muted" role="alert">{error}</p><Link className="mt-6 inline-block font-semibold text-accent hover:underline" to="/learn">Browse curriculum</Link></main>
  const isNew = overallProgress.completedLessons === 0 && !recentLessons.length
  return <main className="mx-auto w-full max-w-320 px-5 py-12 sm:px-10 sm:py-16 lg:px-20"><header className="max-w-2xl"><p className="type-label text-accent">Dashboard</p><h1 className="mt-4 type-h1">Your learning</h1><p className="mt-4 text-muted">Progress is saved as you move through Lumims.</p></header>
    {isNew ? <Card className="mt-10 max-w-2xl"><h2 className="type-h2">Start your learning path</h2><p className="mt-3 text-muted">Your progress will appear here after you begin a lesson.</p>{first ? <Link className="mt-6 inline-block font-semibold text-accent hover:underline" to={`/learn/${curriculum[0].slug}/${first.slug}`}>Start learning</Link> : <Link to="/learn">Browse curriculum</Link>}</Card> : <><section className="mt-10 grid gap-5 lg:grid-cols-[1.35fr_1fr]"><Card><h2 className="type-h2">Overall progress</h2><p className="mt-3 text-sm text-muted">{overallProgress.completedLessons} of {overallProgress.totalLessons} lessons completed</p><ProgressBar className="mt-6" label="Curriculum progress" max={overallProgress.totalLessons} value={overallProgress.completedLessons} /></Card><Card>{continueLearning ? <><p className="type-label text-accent">Continue learning</p><h2 className="mt-3 type-h2">{continueLearning.lesson.title}</h2><p className="mt-2 text-sm text-muted">{continueLearning.topic.title}</p><Link className="mt-6 inline-block font-semibold text-accent hover:underline" to={`/learn/${continueLearning.topic.slug}/${continueLearning.lesson.slug}`}>Continue learning</Link></> : <><h2 className="type-h2">Curriculum complete</h2><p className="mt-3 text-muted">You’ve completed the current Lumims curriculum.</p><Link className="mt-6 inline-block font-semibold text-accent hover:underline" to="/learn">Review curriculum</Link></>}</Card></section>
    <section className="mt-14"><h2 className="type-h2">Topic progress</h2><ol className="mt-6 space-y-3">{curriculum.map((topic) => { const progress = getTopicProgress(topic.lessons.map((lesson) => lesson.id)); const state = progress.completedLessons === progress.totalLessons ? 'Completed' : progress.completedLessons ? 'In progress' : 'Not started'; return <li key={topic.id}><Link className="block rounded-md border border-border bg-surface p-5 hover:border-accent" to={`/learn/${topic.slug}`}><div className="flex justify-between gap-4"><span className="font-semibold">{String(topic.order).padStart(2, '0')} · {topic.title}</span><span className="text-sm text-muted">{state}</span></div><ProgressBar className="mt-3" label={`${progress.completedLessons} of ${progress.totalLessons} lessons`} max={progress.totalLessons} value={progress.completedLessons} /></Link></li> })}</ol></section>
    <section className="mt-14"><h2 className="type-h2">Recently visited</h2>{recentLessons.length ? <ol className="mt-6 divide-y divide-border border-y border-border">{recentLessons.map(({ entry, completed, lastVisitedAt }) => <li key={entry.lesson.id}><Link className="block py-4 hover:text-accent" to={`/learn/${entry.topic.slug}/${entry.lesson.slug}`}><span className="font-semibold">{entry.lesson.title}</span><span className="ml-2 text-sm text-muted">{entry.topic.title} · {new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(lastVisitedAt))}{completed ? ' · Completed' : ''}</span></Link></li>)}</ol> : <p className="mt-4 text-muted">Recently visited lessons will appear here as you learn.</p>}</section></>}</main>
}
